use_frameworks!

target 'ViewAnimator_Example' do
  pod 'ViewAnimator', :path => '../'

  target 'ViewAnimator_Tests' do
    inherit! :search_paths
  end
end

target 'ViewAnimatorTVOS' do
    pod 'ViewAnimator', :path => '../'
end
